#!/bin/sh
# A munki condition to find the names of the PCI card(s) installed on the
# machine and store as 'pci_cards'. 

DEFAULTS="/usr/bin/defaults"
PLUTIL="/usr/bin/plutil"

# Read the location of the ManagedInstallDir from ManagedInstall.plist
MANAGED_INSTALL_DIR="$(${DEFAULTS} read \
/Library/Preferences/ManagedInstalls ManagedInstallDir)"

# Make sure we're outputting our information to "ConditionalItems.plist" 
# (plist is left off since defaults requires this)
COND_ITEMS="${MANAGED_INSTALL_DIR}/ConditionalItems"

# Set the field separator to newline since each unique item is on its own line
IFS=$'\n'

for PCI_CARD in \
  "$(/usr/sbin/system_profiler SPPCIDataType \
  | grep "Name:" \
  | cut -c 13-)"; do 
  # Build an array of values from output of the above command.
  PCI_CARDS+=( ${PCI_CARD} )
done;

# Write the resulting array values to the conditional items plist
"${DEFAULTS}" write "${COND_ITEMS}" "pci_cards" \
  -array "${PCI_CARDS[@]}"

# Convert the plist to from binary to xml so munki can read it.
"${PLUTIL}" -convert xml1 "${COND_ITEMS}".plist

exit 0
